### ISSUE TITLE
malformed multipart-form data: unexpected end of stream

### ISSUE THREAD

**Issue by swznd** [ssttevee/js-cfw-formdata-polyfill#1] opened 2020-01-18 23:34 UTC
I always got error 1101, then I check by try to make request on the worker editor, in the console shows error:
`malformed multipart-form data: unexpected end of stream`

**Comment by ssttevee** [comment] 2020-01-20 16:35
What http client are you using? (i.e fetch API, Python requests module, etc)

Can you post a small example of a failing payload?

**Comment by swznd** [comment] 2020-01-20 18:10
The example payload:

```
POST /user-upload/ HTTP/1.1
Host: host
Cache-Control: no-cache
Postman-Token: 0048aa53-e164-11f2-61dd-57118adf0c95
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"

test
------WebKitFormBoundary7MA4YWxkTrZu0gW--
```

**Comment by ssttevee** [comment] 2020-01-21 06:46
I think I've found the root cause. Postman seems to end the payload with a single `CR` where as the multipart formdata composers that I tested with had end off the payload with a `CRLF`. For future reference, [RFC 2046](https://tools.ietf.org/html/rfc2046#page-43) does not require terminating the payload with `CRLF`, only a non-zero length padding.

Also, the likely reason that you're seeing `unexpected end of stream` on the workers site is because multipart form data requires `CRLF` line endings but when copy and pasting the website, all line endings are normalized to only `LF`.

**Comment by swznd** [comment] 2020-01-21 07:31
but when I using xhr or fetch still get the 500 with error 1101

```
const formData = new FormData();
formData.append('file', 'test');

fetch('https://host/user-upload/', { method: 'POST', body: formData }).then(res => {
    console.log(`status: ${res.status}`);
}).catch(e => {
    console.error(e);
});
```

**Comment by ssttevee** [comment] 2020-01-23 05:53
Yeah, I'll push a fix for this sometime this weekend

**Comment by ssttevee** [comment] 2020-01-23 08:47
try out this new push

**Closed as completed** 2021-01-13 00:44 UTC
